// report-mapper.js
// -----------------------------------------------------------------------------
// Replaces the AR-REST-based fetch/mapping in invoice-mapper.js. Consumes a
// BI Publisher report XML (data model: __Bahaa_Mohamed_zatca_report_xdm)
// instead of calling Oracle's receivablesInvoices REST resource.
//
// Structure observed from the sample file (zatca_report__5___1_.xml):
//   <DATA_DS><G_2>...flat fields, one <G_2> per invoice LINE...</G_2></DATA_DS>
// Header-level fields (invoice number, seller, buyer, totals) are repeated
// on every <G_2> row for a given invoice — this is a flat/denormalized BI
// report shape, not a nested header/lines structure. Multiple lines for the
// same invoice = multiple sibling <G_2> elements sharing the same
// INVOICE_NUMBER; group by that to reassemble one invoice.
//
// IMPORTANT — issues found in the sample data, not fixed silently here:
//   1. BUYER_STREET / BUYER_DISTRICT look transposed in the sample
//      ("District customer" sits in STREET, "street customer" sits in
//      DISTRICT). Left as-is below — check the report's SQL/column mapping
//      rather than assuming this mapper should swap them back, since that's
//      guessing which side is actually wrong.
//   2. LINE_AMOUNT_INCLUSIVE_VAT in the sample equals LINE_NET_AMOUNT exactly
//      (no VAT added) — this field looks unpopulated/unreliable. This mapper
//      does NOT use it; line tax is derived from VAT_CATEGORY_CODE instead
//      (see TAX_CATEGORY_MAP below).
//   3. No SELLER_ADDITIONAL_NUMBER / BUYER_ADDITIONAL_NUMBER column exists in
//      the report at all, but ZATCA's structured address requires an
//      Additional Number (4 digits) alongside Building Number. Seller's
//      falls back to config.js (sellerDefaults/supplierAddressDefault);
//      buyer's has no fallback source yet — stays null, which is legal for a
//      B2C (SIMPLIFIED) buyer but will fail ZATCA validation for B2B if not
//      fixed at the report level before go-live.
//   4. VAT_CATEGORY_CODE is a custom code ("SUNOU_VAT_15"), not a ZATCA
//      category (S/Z/E/O). Mapped explicitly below — extend the map rather
//      than trying to parse the string, since guessing at code meaning is
//      exactly the kind of mistake we already hit once with xml-c14n.
//
// -----------------------------------------------------------------------------
// REPORT COLUMNS REQUIRED (add these to the BI report's data model)
//
// The sample report only contained a standard invoice (388/0100000), so it
// has no columns for credit/debit notes. All 6 ZATCA document types are now
// handled in code, but 4 of them (the credit/debit notes) need report data
// that doesn't exist yet:
//
//   ORIGINAL_INVOICE_NUMBER  required on 381/383 — the invoice being adjusted
//   ADJUSTMENT_REASON        required on 381/383 — ZATCA requires a reason
//   ORIGINAL_INVOICE_DATE    optional — falls back to the chain-store record
//
// Note the original invoice's UUID is deliberately NOT a report column: it's
// generated by this system at submission time, so it's read back from
// chain-store.js. This is why chain-store records must survive — losing them
// makes it impossible to issue a credit note against an older invoice.
//
// Also still missing from the report (needed for B2B compliance):
//   SELLER_ADDITIONAL_NUMBER / BUYER_ADDITIONAL_NUMBER (4-digit)
// -----------------------------------------------------------------------------

import { XMLParser } from 'fast-xml-parser';
import { sellerDefaults, supplierAddressDefault } from './config.js';
import { getPreviousInvoiceHash, getNextInvoiceCounter, getInvoiceRecord } from './chain-store.js';
import { randomUUID } from 'crypto';

const parser = new XMLParser({
  ignoreAttributes: true,
  // IMPORTANT: do NOT let this auto-convert tag values to numbers.
  // INVOICE_SUBTYPE_CODE ("0100000"), postal codes, VAT numbers, etc. all
  // have meaningful leading zeros or need to stay strings; fast-xml-parser's
  // default numeric coercion silently turns "0100000" into 100000, which
  // then re-stringifies as "100000" and corrupts the B2B/B2C prefix check
  // below. Everything that's genuinely numeric (quantities, prices, amounts)
  // is already explicitly parseFloat'd where it's used.
  parseTagValue: false,
  trimValues: true,
});

// ---------------------------------------------------------------------------
// THE 6 ZATCA DOCUMENT TYPES
//
// ZATCA's 6 document types are the cross product of the type code and the
// first two digits of the subtype code:
//
//   INVOICE_TYPE_CODE   INVOICE_SUBTYPE_CODE   Document                Endpoint
//   ------------------------------------------------------------------------------
//   388                 0100000                Standard invoice        clearance
//   381                 0100000                Standard credit note    clearance
//   383                 0100000                Standard debit note     clearance
//   388                 0200000                Simplified invoice      reporting
//   381                 0200000                Simplified credit note  reporting
//   383                 0200000                Simplified debit note   reporting
//
// Standard (01) = B2B, goes to /clearance (synchronous, ZATCA returns a
// cleared invoice). Simplified (02) = B2C, goes to /reporting (async, must
// be reported within 24h).
//
// The remaining 5 digits of the subtype code are boolean flags:
//   3rd = third-party billing, 4th = nominal supply, 5th = export,
//   6th = summary, 7th = self-billed.
// All are "0" for ordinary sales. If you start issuing export invoices or
// self-billed documents, those digits must be set by the report, not here.
// ---------------------------------------------------------------------------
const DOCUMENT_TYPE_BY_CODE = {
  388: 'INVOICE',
  381: 'CREDIT_NOTE',
  383: 'DEBIT_NOTE',
};

// Explicit lookup: custom Oracle VAT category code -> ZATCA category + rate.
// TODO: extend this as you encounter zero-rated/exempt/export codes. Throwing
// on an unmapped code is intentional — silently defaulting to Standard/15%
// would misreport tax on anything that isn't actually standard-rated.
const TAX_CATEGORY_MAP = {
  SUNOU_VAT_15: { zatcaCategory: 'S', percent: 15 },
};

/**
 * Parse the report's raw XML into an array of flat row objects (one per
 * <G_2>, i.e. one per invoice line).
 */
export function parseReportXml(rawXml) {
  const parsed = parser.parse(rawXml);
  const rows = parsed.DATA_DS?.G_2;
  if (!rows) {
    throw new Error('No <G_2> rows found under <DATA_DS> — check the report XML structure.');
  }
  // fast-xml-parser gives a single object (not an array) when there's only
  // one <G_2> element — normalize to always work with an array.
  return Array.isArray(rows) ? rows : [rows];
}

/**
 * Map parsed report rows (all rows for ONE invoice, already grouped by
 * INVOICE_NUMBER by the caller) into the same ZATCA invoice shape
 * invoice-mapper.js used to produce, so index.js/signing-client.js don't
 * need to change.
 */
export function mapReportRowsToZatcaFormat(rows) {
  if (!rows || rows.length === 0) {
    throw new Error('mapReportRowsToZatcaFormat called with no rows.');
  }
  const header = rows[0]; // header-level fields are repeated on every row; use the first

  const invoiceTypeCode = String(header.INVOICE_TYPE_CODE);
  const invoiceTypeCodeName = String(header.INVOICE_SUBTYPE_CODE);
  const categoryPrefix = invoiceTypeCodeName.slice(0, 2);
  const invoiceCategory = categoryPrefix === '01' ? 'STANDARD' : categoryPrefix === '02' ? 'SIMPLIFIED' : null;
  if (!invoiceCategory) {
    throw new Error(`Unrecognized INVOICE_SUBTYPE_CODE prefix "${categoryPrefix}" in "${invoiceTypeCodeName}".`);
  }

  if (!/^0[12]\d{5}$/.test(invoiceTypeCodeName)) {
    throw new Error(
      `Invoice ${header.INVOICE_NUMBER}: INVOICE_SUBTYPE_CODE "${invoiceTypeCodeName}" is malformed — ` +
      `expected 7 digits starting 01 or 02 (e.g. "0100000").`
    );
  }

  // Digits 3-7 are the special-case flags (third-party, nominal supply,
  // export, summary, self-billed). Nothing downstream in this integration
  // handles those cases, so refuse rather than silently emit a document that
  // claims a flag we haven't actually implemented the rules for.
  const flags = invoiceTypeCodeName.slice(2);
  if (flags !== '00000') {
    throw new Error(
      `Invoice ${header.INVOICE_NUMBER}: INVOICE_SUBTYPE_CODE "${invoiceTypeCodeName}" sets special-case ` +
      `flags ("${flags}") for third-party/nominal/export/summary/self-billed supply. This integration ` +
      `only handles ordinary sales ("00000") — those cases need additional UBL fields before they can ` +
      `be issued.`
    );
  }

  // Cross-check: STANDARD (B2B) should have a buyer VAT number; SIMPLIFIED
  // (B2C) is allowed not to. Warn rather than throw — the report is the
  // source of truth for category, but a mismatch is worth knowing about.
  const buyerVat = header.BUYER_VAT ? String(header.BUYER_VAT) : null;
  if (invoiceCategory === 'STANDARD' && !buyerVat) {
    console.warn(
      `Invoice ${header.INVOICE_NUMBER}: INVOICE_SUBTYPE_CODE says STANDARD (B2B) but BUYER_VAT is empty — ` +
      `this will likely fail ZATCA validation.`
    );
  }
  if (invoiceCategory === 'SIMPLIFIED' && buyerVat) {
    console.warn(
      `Invoice ${header.INVOICE_NUMBER}: INVOICE_SUBTYPE_CODE says SIMPLIFIED (B2C) but a BUYER_VAT was ` +
      `provided (${buyerVat}) — double check this was actually meant to be a B2C invoice.`
    );
  }

  let lineExtensionAmount = 0;
  let totalTaxAmount = 0;
  const taxBreakdown = new Map();

  const invoiceLines = rows.map((row, index) => {
    const quantity = parseFloat(row.INVOICED_QUANTITY) || 0;
    const unitPrice = parseFloat(row.UNIT_PRICE) || 0;
    const lineAmount = parseFloat(row.LINE_NET_AMOUNT);
    const netAmount = Number.isFinite(lineAmount) ? lineAmount : quantity * unitPrice;

    const categoryCode = row.VAT_CATEGORY_CODE;
    const taxInfo = TAX_CATEGORY_MAP[categoryCode];
    if (!taxInfo) {
      throw new Error(
        `Line ${row.LINE_NUMBER} (invoice ${header.INVOICE_NUMBER}): unmapped VAT_CATEGORY_CODE ` +
        `"${categoryCode}" — add it to TAX_CATEGORY_MAP in report-mapper.js.`
      );
    }
    const lineTaxAmount = Math.round(netAmount * taxInfo.percent) / 100;

    lineExtensionAmount += netAmount;
    totalTaxAmount += lineTaxAmount;

    const bucket = taxBreakdown.get(taxInfo.zatcaCategory) || {
      taxableAmount: 0,
      taxAmount: 0,
      percent: taxInfo.percent,
    };
    bucket.taxableAmount += netAmount;
    bucket.taxAmount += lineTaxAmount;
    taxBreakdown.set(taxInfo.zatcaCategory, bucket);

    return {
      id: index + 1,
      quantity,
      unitCode: 'C62',
      lineExtensionAmount: netAmount,
      taxAmount: lineTaxAmount,
      itemName: row.ITEM_NAME || `Line ${index + 1}`,
      taxCategoryId: taxInfo.zatcaCategory,
      taxPercent: taxInfo.percent,
      priceAmount: unitPrice,
    };
  });

  const taxSubtotals = Array.from(taxBreakdown.entries()).map(([taxCategoryId, v]) => ({
    taxableAmount: v.taxableAmount,
    taxAmount: v.taxAmount,
    percent: v.percent,
    taxCategoryId,
  }));

  // Cross-check computed totals against the report's own header totals —
  // don't silently trust either source if they disagree.
  const reportedTotalVat = parseFloat(header.TOTAL_VAT_AMOUNT);
  if (Number.isFinite(reportedTotalVat) && Math.abs(reportedTotalVat - totalTaxAmount) > 0.01) {
    console.warn(
      `Invoice ${header.INVOICE_NUMBER}: computed VAT (${totalTaxAmount}) doesn't match report's ` +
      `TOTAL_VAT_AMOUNT (${reportedTotalVat}) — using the computed value. Check VAT_CATEGORY_CODE mapping ` +
      `and/or the report's own calculation.`
    );
  }

  const taxInclusiveAmount = lineExtensionAmount + totalTaxAmount;

  const previousInvoiceHash = getPreviousInvoiceHash();
  const invoiceCounterValue = getNextInvoiceCounter();

  const documentType = DOCUMENT_TYPE_BY_CODE[invoiceTypeCode];
  if (!documentType) {
    throw new Error(
      `Invoice ${header.INVOICE_NUMBER}: unrecognized INVOICE_TYPE_CODE "${invoiceTypeCode}". ` +
      `ZATCA only accepts 388 (invoice), 381 (credit note), or 383 (debit note).`
    );
  }

  // The 6 ZATCA document types are the cross product of:
  //   {388 invoice, 381 credit note, 383 debit note} x {01 standard, 02 simplified}
  // Both halves come from the report (INVOICE_TYPE_CODE and
  // INVOICE_SUBTYPE_CODE) and both have already been validated above, so any
  // combination reaching this point is one of the 6.

  // Credit notes (381) and debit notes (383) are NOT valid without a
  // reference to the invoice they adjust — ZATCA rejects them outright.
  // Build the extra CreditNoteData fields @talha7k/zatca requires here.
  let creditNoteFields = null;
  if (documentType !== 'INVOICE') {
    creditNoteFields = resolveCreditNoteFields(header, documentType);
  }

  return {
    invoiceNumber: String(header.INVOICE_NUMBER),
    uuid: randomUUID(),
    invoiceCounter: invoiceCounterValue, // NOTE: @talha7k/zatca's InvoiceData type calls this `invoiceCounter`, not `invoiceCounterValue` — using the wrong key here wouldn't crash (it's optional) but would silently omit the ICV from the generated XML, breaking the required hash-chain document reference with no error at all.
    previousInvoiceHash,
    issueDate: String(header.ISSUE_DATE),
    issueTime: String(header.ISSUE_TIME),
    actualDeliveryDate: header.ACTUAL_DELIVERY_DATE ? String(header.ACTUAL_DELIVERY_DATE) : null,
    paymentMeansCode: header.PAYMENT_MEANS ? String(header.PAYMENT_MEANS) : null,
    invoiceTypeCode,
    invoiceTypeCodeName,
    invoiceCategory,
    // Required by @talha7k/zatca's InvoiceData type — this was missing
    // entirely before, which is what actually crashed generateInvoiceXml
    // (escapeXml(undefined).replace(...)).
    profileId: invoiceCategory === 'STANDARD' ? 'clearance:1.0' : 'reporting:1.0',
    currencyCode: header.CURRENCY_CODE || 'SAR',
    documentReferences: [],

    supplier: {
      name: header.SELLER_NAME || sellerDefaults.name,
      nameEn: sellerDefaults.name,
      nameAr: sellerDefaults.nameAr,
      vatNumber: header.SELLER_VAT ? String(header.SELLER_VAT) : sellerDefaults.vatNumber,
      crNumber: header.SELLER_CRN ? String(header.SELLER_CRN) : sellerDefaults.crNumber,
      registrationName: header.SELLER_NAME || sellerDefaults.name,
      address: {
        street: header.SELLER_STREET || supplierAddressDefault.street,
        building: header.SELLER_BUILDING_NUMBER || supplierAddressDefault.building,
        // Report has no additional-number column — always from config for now.
        additionalNumber: supplierAddressDefault.additionalNumber,
        district: header.SELLER_DISTRICT || supplierAddressDefault.district,
        city: header.SELLER_CITY || supplierAddressDefault.city,
        postalCode: header.SELLER_POSTAL_ZONE || supplierAddressDefault.postalCode,
        countryCode: header.SELLER_COUNTRY || supplierAddressDefault.countryCode,
      },
    },

    customer: {
      name: header.BUYER_NAME || 'Unknown Customer',
      nameEn: header.BUYER_NAME || 'Unknown Customer',
      nameAr: header.BUYER_NAME || 'Unknown Customer',
      // @talha7k/zatca's CustomerInfo.vatNumber is a required string, not
      // nullable — '' (not null) for B2C, or generateInvoiceXml crashes the
      // same way the missing profileId did above.
      vatNumber: buyerVat || '',
      registrationName: header.BUYER_NAME || 'Unknown Customer',
      address: {
        street: header.BUYER_STREET || null,
        building: header.BUYER_BUILDING_NUMBER || null,
        additionalNumber: null, // TODO: no report column for this yet
        district: header.BUYER_DISTRICT || null,
        city: header.BUYER_CITY || null,
        postalCode: header.BUYER_POSTAL_ZONE || null,
        countryCode: header.BUYER_COUNTRY || 'SA',
      },
    },

    lineExtensionAmount,
    taxExclusiveAmount: lineExtensionAmount,
    taxInclusiveAmount,
    payableAmount: parseFloat(header.AMOUNT_DUE) || taxInclusiveAmount,
    taxAmount: totalTaxAmount,
    taxSubtotals,
    invoiceLines,

    // Which of the 6 ZATCA document types this is. index.js uses this to
    // dispatch to generateInvoiceXml vs generateCreditNoteXml — the package
    // has separate generators and using the wrong one silently omits the
    // BillingReference/InstructionNote blocks that 381/383 require.
    documentType,

    // For 381/383 only: originalInvoiceNumber, originalInvoiceUuid,
    // originalInvoiceDate, reason — the shape CreditNoteData expects.
    // Spread (not nested) because generateCreditNoteXml reads them off the
    // top level of the object.
    ...(creditNoteFields || {}),
  };
}

/**
 * Build the extra fields a credit note (381) or debit note (383) needs on
 * top of the base invoice shape.
 *
 * @talha7k/zatca's CreditNoteData type requires all four of:
 *   originalInvoiceNumber, originalInvoiceUuid, originalInvoiceDate, reason
 * and generateCreditNoteXml renders them into cac:BillingReference and
 * cac:PaymentMeans/cbc:InstructionNote.
 *
 * The originalInvoiceUuid is the one that can't be recovered from the report:
 * it's the UUID *we* generated when we submitted the original invoice, so it
 * only exists in our own chain store. That's why chain-store.js records
 * uuid/issueDate per invoice number.
 */
function resolveCreditNoteFields(header, documentType) {
  const label = documentType === 'CREDIT_NOTE' ? 'Credit note' : 'Debit note';

  const originalInvoiceNumber = header.ORIGINAL_INVOICE_NUMBER
    ? String(header.ORIGINAL_INVOICE_NUMBER)
    : null;

  if (!originalInvoiceNumber) {
    throw new Error(
      `${label} ${header.INVOICE_NUMBER} has no ORIGINAL_INVOICE_NUMBER. ZATCA requires every ` +
      `credit/debit note to reference the invoice it adjusts (cac:BillingReference). ` +
      `Add an ORIGINAL_INVOICE_NUMBER column to the BI report's data model — see the ` +
      `"REPORT COLUMNS REQUIRED" note at the top of this file.`
    );
  }

  const record = getInvoiceRecord(originalInvoiceNumber);

  // The original invoice's UUID cannot be reconstructed — it was randomly
  // generated at submission time. If it isn't in the chain store, this note
  // cannot be built correctly, so fail loudly rather than emit a note with a
  // fabricated or empty UUID that ZATCA will reject (or worse, accept
  // against the wrong document).
  if (!record?.uuid) {
    throw new Error(
      `${label} ${header.INVOICE_NUMBER} references original invoice ${originalInvoiceNumber}, ` +
      `but there's no chain-store record with its UUID. ZATCA needs the original invoice's UUID ` +
      `in cac:BillingReference. This happens when the original invoice was issued before this ` +
      `system went live, or was submitted from a different environment/chain store. ` +
      `You'll need to recover that UUID (e.g. from the original submitted XML) before this note ` +
      `can be issued.`
    );
  }

  const reason =
    (header.ADJUSTMENT_REASON && String(header.ADJUSTMENT_REASON).trim()) ||
    (header.REASON && String(header.REASON).trim()) ||
    null;

  if (!reason) {
    throw new Error(
      `${label} ${header.INVOICE_NUMBER} has no ADJUSTMENT_REASON. ZATCA requires a reason for ` +
      `credit/debit notes (rendered as cbc:InstructionNote). Add an ADJUSTMENT_REASON column to ` +
      `the BI report.`
    );
  }

  return {
    originalInvoiceNumber,
    originalInvoiceUuid: record.uuid,
    originalInvoiceDate: record.issueDate || String(header.ORIGINAL_INVOICE_DATE || ''),
    reason,
  };
}

/**
 * Convenience one-shot: raw XML string -> ZATCA invoice objects (plural,
 * since a single report pull could in principle contain more than one
 * invoice's rows — grouped by INVOICE_NUMBER).
 */
export function mapReportXmlToZatcaFormat(rawXml) {
  const rows = parseReportXml(rawXml);
  const byInvoiceNumber = new Map();
  for (const row of rows) {
    const key = String(row.INVOICE_NUMBER);
    if (!byInvoiceNumber.has(key)) byInvoiceNumber.set(key, []);
    byInvoiceNumber.get(key).push(row);
  }
  return Array.from(byInvoiceNumber.values()).map(mapReportRowsToZatcaFormat);
}